//
// Created by guila on 06/06/18.
//

#ifndef ALGORITHMS_AND_DATA_STRUCTURES_VERTEXCOVER_H
#define ALGORITHMS_AND_DATA_STRUCTURES_VERTEXCOVER_H


class vertexCover {

};


#endif //ALGORITHMS_AND_DATA_STRUCTURES_VERTEXCOVER_H
