//
// Created by guila on 06/06/18.
//

#ifndef ALGORITHMS_AND_DATA_STRUCTURES_BINPACKING_H
#define ALGORITHMS_AND_DATA_STRUCTURES_BINPACKING_H


class binPacking {

};


#endif //ALGORITHMS_AND_DATA_STRUCTURES_BINPACKING_H
