//
// Created by guila on 22/05/18.
//

#ifndef ALGORITHMS_AND_DATA_STRUCTURES_NQUEENS_H
#define ALGORITHMS_AND_DATA_STRUCTURES_NQUEENS_H


class nQueens {

};


#endif //ALGORITHMS_AND_DATA_STRUCTURES_NQUEENS_H
